// <auto-generated />
namespace VPA2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class clients1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clients1));
        
        string IMigrationMetadata.Id
        {
            get { return "201501111735092_clients1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
